version: '3'

services:
  app:
    container_name: 'trybesmith-app'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    container_name: 'database-trybesmith'
    image: mysql:5.7.31
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    volumes:
    - ./mysql-dump:/docker-entrypoint-initdb.d

